#
# MIT License
#
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
name: Chart Testing

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      charts:
        description: List of Changed Charts
        required: true
        type: string
      helm-version:
        description: 'Version of Helm to Intall'
        required: false
        type: string
        default: 'v3.11.3'

jobs:
  run:
    name: Chart Testing
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix: ${{ fromJSON(inputs.charts) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ inputs.helm-version }}

      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run Helm Unittest
        run: |
          helm unittest --color -t Junit -o report.xml ./charts/${{ matrix.chart }}
          if [ "$(wc -l < report.xml)" -eq 1 ] && grep -q "^<testsuites></testsuites>$" report.xml; then
            echo "# ${{ matrix.chart }}" >> $GITHUB_STEP_SUMMARY
            echo "Error: Chart does not contain any unit tests" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Test Summary
        if: ${{ ! cancelled() }}
        uses: test-summary/action@v2
        with:
          paths: |
            ${{ github.workspace }}/report.xml
