---
name: List Changed Charts

on:
  workflow_call:
    outputs:
      charts:
        description: List of changed charts
        value: ${{ jobs.run.outputs.charts }}
      count:
        description: Number of changed charts
        value: ${{ jobs.run.outputs.count }}

permissions:
  contents: read


jobs:
  run:
    name: Changed Charts
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Count Changed Charts
        id: count
        run: >
          git diff --name-only HEAD HEAD^ charts/ | cut -d/ -f1,2 | uniq | wc -l
          echo "count=$(git diff --name-only HEAD HEAD^ charts/ | cut -d/ -f1,2 | uniq | wc -l)" >> $GITHUB_OUTPUT

      - name: List Changed Charts
        id: list
        run: >
           git diff --name-only HEAD HEAD^ charts/
           git diff --name-only HEAD HEAD^ charts/ | cut -d/ -f1,2
           git diff --name-only HEAD HEAD^ charts/ | cut -d/ -f1,2 | xargs -I{file} dirname {file}
           echo "charts=$(git diff --name-only HEAD HEAD^ charts/ | cut -d/ -f1,2 | xargs -I{file} dirname {file} |
           uniq | jq -cR 'split(" ") | {chart: .}')" >> $GITHUB_OUTPUT

      - name: Display changed chart
        run: |
          echo "Charts: ${{ steps.list.outputs.charts }}"
          echo "Count: ${{ steps.count.outputs.count }}"

    outputs:
      charts: ${{ steps.list.outputs.charts }}
      count: ${{ steps.count.outputs.count }}
